-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity do_compute_do_compute_Pipeline_VITIS_LOOP_53_1_VITIS_LOOP_54_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    spillage_flag_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    spillage_flag_ce0 : OUT STD_LOGIC;
    spillage_flag_we0 : OUT STD_LOGIC;
    spillage_flag_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    spillage_level_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    spillage_level_ce0 : OUT STD_LOGIC;
    spillage_level_we0 : OUT STD_LOGIC;
    spillage_level_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    spillage_from_neigh_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    spillage_from_neigh_ce0 : OUT STD_LOGIC;
    spillage_from_neigh_we0 : OUT STD_LOGIC;
    spillage_from_neigh_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    spillage_from_neigh_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    spillage_from_neigh_1_ce0 : OUT STD_LOGIC;
    spillage_from_neigh_1_we0 : OUT STD_LOGIC;
    spillage_from_neigh_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    spillage_from_neigh_2_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    spillage_from_neigh_2_ce0 : OUT STD_LOGIC;
    spillage_from_neigh_2_we0 : OUT STD_LOGIC;
    spillage_from_neigh_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    spillage_from_neigh_3_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    spillage_from_neigh_3_ce0 : OUT STD_LOGIC;
    spillage_from_neigh_3_we0 : OUT STD_LOGIC;
    spillage_from_neigh_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    water_level_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    water_level_ce0 : OUT STD_LOGIC;
    water_level_we0 : OUT STD_LOGIC;
    water_level_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    water_level_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    water_level_1_ce0 : OUT STD_LOGIC;
    water_level_1_we0 : OUT STD_LOGIC;
    water_level_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    water_level_2_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    water_level_2_ce0 : OUT STD_LOGIC;
    water_level_2_we0 : OUT STD_LOGIC;
    water_level_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of do_compute_do_compute_Pipeline_VITIS_LOOP_53_1_VITIS_LOOP_54_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv13_1FA4 : STD_LOGIC_VECTOR (12 downto 0) := "1111110100100";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_5A : STD_LOGIC_VECTOR (6 downto 0) := "1011010";
    constant ap_const_lv7_3 : STD_LOGIC_VECTOR (6 downto 0) := "0000011";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv15_AB : STD_LOGIC_VECTOR (14 downto 0) := "000000010101011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv13_5A : STD_LOGIC_VECTOR (12 downto 0) := "0000001011010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln53_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln52_fu_262_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln52_reg_418 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln52_reg_418_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln53_fu_270_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln53_reg_425 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln53_reg_425_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln58_fu_359_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_reg_441 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_reg_441_pp0_iter3_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_reg_441_pp0_iter4_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_reg_441_pp0_iter5_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_reg_441_pp0_iter6_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_reg_441_pp0_iter7_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_reg_441_pp0_iter8_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_reg_441_pp0_iter9_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_reg_441_pp0_iter10_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln52_fu_374_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln52_reg_446 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln59_1_fu_365_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln58_2_fu_378_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal col_pos_fu_76 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln54_fu_288_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_col_pos_load : STD_LOGIC_VECTOR (6 downto 0);
    signal row_pos_fu_80 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal ap_sig_allocacmp_row_pos_load : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten_fu_84 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal add_ln53_1_fu_238_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (12 downto 0);
    signal spillage_flag_we0_local : STD_LOGIC;
    signal spillage_flag_ce0_local : STD_LOGIC;
    signal spillage_level_we0_local : STD_LOGIC;
    signal spillage_level_ce0_local : STD_LOGIC;
    signal spillage_from_neigh_we0_local : STD_LOGIC;
    signal spillage_from_neigh_ce0_local : STD_LOGIC;
    signal spillage_from_neigh_1_we0_local : STD_LOGIC;
    signal spillage_from_neigh_1_ce0_local : STD_LOGIC;
    signal spillage_from_neigh_2_we0_local : STD_LOGIC;
    signal spillage_from_neigh_2_ce0_local : STD_LOGIC;
    signal spillage_from_neigh_3_we0_local : STD_LOGIC;
    signal spillage_from_neigh_3_ce0_local : STD_LOGIC;
    signal water_level_1_we0_local : STD_LOGIC;
    signal water_level_1_ce0_local : STD_LOGIC;
    signal water_level_we0_local : STD_LOGIC;
    signal water_level_ce0_local : STD_LOGIC;
    signal water_level_2_we0_local : STD_LOGIC;
    signal water_level_2_ce0_local : STD_LOGIC;
    signal icmp_ln54_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln53_fu_250_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_282_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_316_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl_fu_309_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln58_fu_323_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln52_fu_339_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln52_fu_339_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln52_fu_339_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_33_fu_345_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln58_fu_327_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln58_1_fu_355_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_384_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_282_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_384_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_384_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_384_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_384_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_384_p20 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln52_fu_339_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component do_compute_urem_7ns_3ns_2_11_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component do_compute_mul_7ns_9ns_15_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component do_compute_mac_muladd_7ns_7ns_7ns_13_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component do_compute_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    urem_7ns_3ns_2_11_1_U1 : component do_compute_urem_7ns_3ns_2_11_1
    generic map (
        ID => 1,
        NUM_STAGE => 11,
        din0_WIDTH => 7,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln52_fu_262_p3,
        din1 => grp_fu_282_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_282_p2);

    mul_7ns_9ns_15_1_1_U2 : component do_compute_mul_7ns_9ns_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 7,
        din1_WIDTH => 9,
        dout_WIDTH => 15)
    port map (
        din0 => mul_ln52_fu_339_p0,
        din1 => mul_ln52_fu_339_p1,
        dout => mul_ln52_fu_339_p2);

    mac_muladd_7ns_7ns_7ns_13_4_1_U3 : component do_compute_mac_muladd_7ns_7ns_7ns_13_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 7,
        din1_WIDTH => 7,
        din2_WIDTH => 7,
        dout_WIDTH => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_384_p0,
        din1 => grp_fu_384_p1,
        din2 => grp_fu_384_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_384_p3);

    flow_control_loop_pipe_sequential_init_U : component do_compute_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    col_pos_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln53_fu_232_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    col_pos_fu_76 <= add_ln54_fu_288_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    col_pos_fu_76 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln53_fu_232_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_84 <= add_ln53_1_fu_238_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_84 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    row_pos_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln53_fu_232_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    row_pos_fu_80 <= select_ln53_fu_270_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    row_pos_fu_80 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln58_reg_441 <= add_ln58_fu_359_p2;
                add_ln58_reg_441_pp0_iter10_reg <= add_ln58_reg_441_pp0_iter9_reg;
                add_ln58_reg_441_pp0_iter3_reg <= add_ln58_reg_441;
                add_ln58_reg_441_pp0_iter4_reg <= add_ln58_reg_441_pp0_iter3_reg;
                add_ln58_reg_441_pp0_iter5_reg <= add_ln58_reg_441_pp0_iter4_reg;
                add_ln58_reg_441_pp0_iter6_reg <= add_ln58_reg_441_pp0_iter5_reg;
                add_ln58_reg_441_pp0_iter7_reg <= add_ln58_reg_441_pp0_iter6_reg;
                add_ln58_reg_441_pp0_iter8_reg <= add_ln58_reg_441_pp0_iter7_reg;
                add_ln58_reg_441_pp0_iter9_reg <= add_ln58_reg_441_pp0_iter8_reg;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                trunc_ln52_reg_446 <= trunc_ln52_fu_374_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                select_ln52_reg_418 <= select_ln52_fu_262_p3;
                select_ln52_reg_418_pp0_iter1_reg <= select_ln52_reg_418;
                select_ln53_reg_425 <= select_ln53_fu_270_p3;
                select_ln53_reg_425_pp0_iter1_reg <= select_ln53_reg_425;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln53_1_fu_238_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv13_1));
    add_ln53_fu_250_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_row_pos_load) + unsigned(ap_const_lv7_1));
    add_ln54_fu_288_p2 <= std_logic_vector(unsigned(select_ln52_fu_262_p3) + unsigned(ap_const_lv7_1));
    add_ln58_fu_359_p2 <= std_logic_vector(unsigned(sub_ln58_fu_327_p2) + unsigned(zext_ln58_1_fu_355_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln53_fu_232_p2)
    begin
        if (((icmp_ln53_fu_232_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter10_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_col_pos_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, col_pos_fu_76, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_col_pos_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_col_pos_load <= col_pos_fu_76;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_84)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_84;
        end if; 
    end process;


    ap_sig_allocacmp_row_pos_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, row_pos_fu_80)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_row_pos_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_row_pos_load <= row_pos_fu_80;
        end if; 
    end process;

    grp_fu_282_p1 <= ap_const_lv7_3(3 - 1 downto 0);
    grp_fu_384_p0 <= grp_fu_384_p00(7 - 1 downto 0);
    grp_fu_384_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln53_fu_270_p3),13));
    grp_fu_384_p1 <= ap_const_lv13_5A(7 - 1 downto 0);
    grp_fu_384_p2 <= grp_fu_384_p20(7 - 1 downto 0);
    grp_fu_384_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln52_reg_418_pp0_iter1_reg),13));
    icmp_ln53_fu_232_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv13_1FA4) else "0";
    icmp_ln54_fu_256_p2 <= "1" when (ap_sig_allocacmp_col_pos_load = ap_const_lv7_5A) else "0";
    mul_ln52_fu_339_p0 <= mul_ln52_fu_339_p00(7 - 1 downto 0);
    mul_ln52_fu_339_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln52_reg_418_pp0_iter1_reg),15));
    mul_ln52_fu_339_p1 <= ap_const_lv15_AB(9 - 1 downto 0);
    p_shl_fu_309_p3 <= (select_ln53_reg_425_pp0_iter1_reg & ap_const_lv5_0);
    select_ln52_fu_262_p3 <= 
        ap_const_lv7_0 when (icmp_ln54_fu_256_p2(0) = '1') else 
        ap_sig_allocacmp_col_pos_load;
    select_ln53_fu_270_p3 <= 
        add_ln53_fu_250_p2 when (icmp_ln54_fu_256_p2(0) = '1') else 
        ap_sig_allocacmp_row_pos_load;
    spillage_flag_address0 <= zext_ln59_1_fu_365_p1(13 - 1 downto 0);
    spillage_flag_ce0 <= spillage_flag_ce0_local;

    spillage_flag_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_flag_ce0_local <= ap_const_logic_1;
        else 
            spillage_flag_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_flag_d0 <= ap_const_lv32_0;
    spillage_flag_we0 <= spillage_flag_we0_local;

    spillage_flag_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_flag_we0_local <= ap_const_logic_1;
        else 
            spillage_flag_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_1_address0 <= zext_ln59_1_fu_365_p1(13 - 1 downto 0);
    spillage_from_neigh_1_ce0 <= spillage_from_neigh_1_ce0_local;

    spillage_from_neigh_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_1_ce0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_1_d0 <= ap_const_lv32_0;
    spillage_from_neigh_1_we0 <= spillage_from_neigh_1_we0_local;

    spillage_from_neigh_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_1_we0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_2_address0 <= zext_ln59_1_fu_365_p1(13 - 1 downto 0);
    spillage_from_neigh_2_ce0 <= spillage_from_neigh_2_ce0_local;

    spillage_from_neigh_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_2_ce0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_2_d0 <= ap_const_lv32_0;
    spillage_from_neigh_2_we0 <= spillage_from_neigh_2_we0_local;

    spillage_from_neigh_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_2_we0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_3_address0 <= zext_ln59_1_fu_365_p1(13 - 1 downto 0);
    spillage_from_neigh_3_ce0 <= spillage_from_neigh_3_ce0_local;

    spillage_from_neigh_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_3_ce0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_3_d0 <= ap_const_lv32_0;
    spillage_from_neigh_3_we0 <= spillage_from_neigh_3_we0_local;

    spillage_from_neigh_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_3_we0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_address0 <= zext_ln59_1_fu_365_p1(13 - 1 downto 0);
    spillage_from_neigh_ce0 <= spillage_from_neigh_ce0_local;

    spillage_from_neigh_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_ce0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_d0 <= ap_const_lv32_0;
    spillage_from_neigh_we0 <= spillage_from_neigh_we0_local;

    spillage_from_neigh_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_we0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_level_address0 <= zext_ln59_1_fu_365_p1(13 - 1 downto 0);
    spillage_level_ce0 <= spillage_level_ce0_local;

    spillage_level_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_level_ce0_local <= ap_const_logic_1;
        else 
            spillage_level_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_level_d0 <= ap_const_lv32_0;
    spillage_level_we0 <= spillage_level_we0_local;

    spillage_level_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_level_we0_local <= ap_const_logic_1;
        else 
            spillage_level_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln58_fu_327_p2 <= std_logic_vector(unsigned(p_shl_fu_309_p3) - unsigned(zext_ln58_fu_323_p1));
    tmp_33_fu_345_p4 <= mul_ln52_fu_339_p2(14 downto 9);
    tmp_fu_316_p3 <= (select_ln53_reg_425_pp0_iter1_reg & ap_const_lv1_0);
    trunc_ln52_fu_374_p1 <= grp_fu_282_p2(2 - 1 downto 0);
    water_level_1_address0 <= zext_ln58_2_fu_378_p1(12 - 1 downto 0);
    water_level_1_ce0 <= water_level_1_ce0_local;

    water_level_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            water_level_1_ce0_local <= ap_const_logic_1;
        else 
            water_level_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    water_level_1_d0 <= ap_const_lv32_0;
    water_level_1_we0 <= water_level_1_we0_local;

    water_level_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln52_reg_446)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln52_reg_446 = ap_const_lv2_1))) then 
            water_level_1_we0_local <= ap_const_logic_1;
        else 
            water_level_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    water_level_2_address0 <= zext_ln58_2_fu_378_p1(12 - 1 downto 0);
    water_level_2_ce0 <= water_level_2_ce0_local;

    water_level_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            water_level_2_ce0_local <= ap_const_logic_1;
        else 
            water_level_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    water_level_2_d0 <= ap_const_lv32_0;
    water_level_2_we0 <= water_level_2_we0_local;

    water_level_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln52_reg_446)
    begin
        if ((not((trunc_ln52_reg_446 = ap_const_lv2_0)) and not((trunc_ln52_reg_446 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            water_level_2_we0_local <= ap_const_logic_1;
        else 
            water_level_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    water_level_address0 <= zext_ln58_2_fu_378_p1(12 - 1 downto 0);
    water_level_ce0 <= water_level_ce0_local;

    water_level_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            water_level_ce0_local <= ap_const_logic_1;
        else 
            water_level_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    water_level_d0 <= ap_const_lv32_0;
    water_level_we0 <= water_level_we0_local;

    water_level_we0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001, trunc_ln52_reg_446)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (trunc_ln52_reg_446 = ap_const_lv2_0))) then 
            water_level_we0_local <= ap_const_logic_1;
        else 
            water_level_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln58_1_fu_355_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_33_fu_345_p4),12));
    zext_ln58_2_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln58_reg_441_pp0_iter10_reg),64));
    zext_ln58_fu_323_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_316_p3),12));
    zext_ln59_1_fu_365_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_384_p3),64));
end behav;
