-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity do_compute_do_compute_Pipeline_VITIS_LOOP_76_5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_clouds_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    p_clouds_ce0 : OUT STD_LOGIC;
    p_clouds_we0 : OUT STD_LOGIC;
    p_clouds_d0 : OUT STD_LOGIC_VECTOR (223 downto 0);
    p_clouds_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    p_clouds_ce1 : OUT STD_LOGIC;
    p_clouds_q1 : IN STD_LOGIC_VECTOR (223 downto 0);
    grp_fu_454_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_454_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_454_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_454_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_454_p_ce : OUT STD_LOGIC;
    grp_fu_459_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_459_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_459_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_459_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_459_p_ce : OUT STD_LOGIC;
    grp_fu_485_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_485_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_485_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_485_p_ce : OUT STD_LOGIC;
    grp_fu_490_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_490_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_490_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_490_p_ce : OUT STD_LOGIC );
end;


architecture behav of do_compute_do_compute_Pipeline_VITIS_LOOP_76_5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_42700000 : STD_LOGIC_VECTOR (31 downto 0) := "01000010011100000000000000000000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln76_fu_103_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_clouds_addr_reg_212 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter8_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter9_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter10_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter11_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter12_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter13_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter14_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter15_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter16_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter17_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter18_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter19_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_addr_reg_212_pp0_iter20_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln3_reg_218 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln78_fu_135_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln78_reg_223 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln78_reg_223_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln78_reg_223_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln78_reg_223_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln78_reg_223_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln78_reg_223_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln78_reg_223_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln78_reg_223_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln78_reg_223_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln78_reg_223_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln78_reg_223_pp0_iter11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln78_reg_223_pp0_iter12_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln78_reg_223_pp0_iter13_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln4_reg_228 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln79_1_reg_233 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln79_1_reg_233_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln79_1_reg_233_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln79_1_reg_233_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln79_1_reg_233_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln79_1_reg_233_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln79_1_reg_233_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln79_1_reg_233_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln79_1_reg_233_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln79_1_reg_233_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln79_1_reg_233_pp0_iter11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln79_1_reg_233_pp0_iter12_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln79_1_reg_233_pp0_iter13_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_reg_238 : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter2_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter3_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter4_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter5_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter6_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter7_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter8_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter9_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter10_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter11_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter12_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter13_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter14_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter15_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter16_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter17_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter18_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter19_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal tmp_s_reg_238_pp0_iter20_reg : STD_LOGIC_VECTOR (159 downto 0);
    signal bitcast_ln78_fu_169_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln79_fu_173_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal div_reg_253 : STD_LOGIC_VECTOR (31 downto 0);
    signal div1_reg_258 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln78_1_fu_177_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln79_1_fu_181_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add1_reg_273 : STD_LOGIC_VECTOR (31 downto 0);
    signal add2_reg_278 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln76_fu_115_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal cloud_fu_56 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln76_fu_109_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_cloud_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_clouds_ce1_local : STD_LOGIC;
    signal p_clouds_we0_local : STD_LOGIC;
    signal or_ln_fu_191_p4 : STD_LOGIC_VECTOR (223 downto 0);
    signal p_clouds_ce0_local : STD_LOGIC;
    signal bitcast_ln79_2_fu_188_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln78_2_fu_185_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component do_compute_faddfsub_32ns_32ns_32_7_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component do_compute_fdiv_32ns_32ns_32_12_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component do_compute_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component do_compute_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter20_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    cloud_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln76_fu_103_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    cloud_fu_56 <= add_ln76_fu_109_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    cloud_fu_56 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add1_reg_273 <= grp_fu_454_p_dout0;
                add2_reg_278 <= grp_fu_459_p_dout0;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                div1_reg_258 <= grp_fu_490_p_dout0;
                div_reg_253 <= grp_fu_485_p_dout0;
                p_clouds_addr_reg_212_pp0_iter10_reg <= p_clouds_addr_reg_212_pp0_iter9_reg;
                p_clouds_addr_reg_212_pp0_iter11_reg <= p_clouds_addr_reg_212_pp0_iter10_reg;
                p_clouds_addr_reg_212_pp0_iter12_reg <= p_clouds_addr_reg_212_pp0_iter11_reg;
                p_clouds_addr_reg_212_pp0_iter13_reg <= p_clouds_addr_reg_212_pp0_iter12_reg;
                p_clouds_addr_reg_212_pp0_iter14_reg <= p_clouds_addr_reg_212_pp0_iter13_reg;
                p_clouds_addr_reg_212_pp0_iter15_reg <= p_clouds_addr_reg_212_pp0_iter14_reg;
                p_clouds_addr_reg_212_pp0_iter16_reg <= p_clouds_addr_reg_212_pp0_iter15_reg;
                p_clouds_addr_reg_212_pp0_iter17_reg <= p_clouds_addr_reg_212_pp0_iter16_reg;
                p_clouds_addr_reg_212_pp0_iter18_reg <= p_clouds_addr_reg_212_pp0_iter17_reg;
                p_clouds_addr_reg_212_pp0_iter19_reg <= p_clouds_addr_reg_212_pp0_iter18_reg;
                p_clouds_addr_reg_212_pp0_iter20_reg <= p_clouds_addr_reg_212_pp0_iter19_reg;
                p_clouds_addr_reg_212_pp0_iter2_reg <= p_clouds_addr_reg_212_pp0_iter1_reg;
                p_clouds_addr_reg_212_pp0_iter3_reg <= p_clouds_addr_reg_212_pp0_iter2_reg;
                p_clouds_addr_reg_212_pp0_iter4_reg <= p_clouds_addr_reg_212_pp0_iter3_reg;
                p_clouds_addr_reg_212_pp0_iter5_reg <= p_clouds_addr_reg_212_pp0_iter4_reg;
                p_clouds_addr_reg_212_pp0_iter6_reg <= p_clouds_addr_reg_212_pp0_iter5_reg;
                p_clouds_addr_reg_212_pp0_iter7_reg <= p_clouds_addr_reg_212_pp0_iter6_reg;
                p_clouds_addr_reg_212_pp0_iter8_reg <= p_clouds_addr_reg_212_pp0_iter7_reg;
                p_clouds_addr_reg_212_pp0_iter9_reg <= p_clouds_addr_reg_212_pp0_iter8_reg;
                tmp_s_reg_238_pp0_iter10_reg <= tmp_s_reg_238_pp0_iter9_reg;
                tmp_s_reg_238_pp0_iter11_reg <= tmp_s_reg_238_pp0_iter10_reg;
                tmp_s_reg_238_pp0_iter12_reg <= tmp_s_reg_238_pp0_iter11_reg;
                tmp_s_reg_238_pp0_iter13_reg <= tmp_s_reg_238_pp0_iter12_reg;
                tmp_s_reg_238_pp0_iter14_reg <= tmp_s_reg_238_pp0_iter13_reg;
                tmp_s_reg_238_pp0_iter15_reg <= tmp_s_reg_238_pp0_iter14_reg;
                tmp_s_reg_238_pp0_iter16_reg <= tmp_s_reg_238_pp0_iter15_reg;
                tmp_s_reg_238_pp0_iter17_reg <= tmp_s_reg_238_pp0_iter16_reg;
                tmp_s_reg_238_pp0_iter18_reg <= tmp_s_reg_238_pp0_iter17_reg;
                tmp_s_reg_238_pp0_iter19_reg <= tmp_s_reg_238_pp0_iter18_reg;
                tmp_s_reg_238_pp0_iter20_reg <= tmp_s_reg_238_pp0_iter19_reg;
                tmp_s_reg_238_pp0_iter2_reg <= tmp_s_reg_238;
                tmp_s_reg_238_pp0_iter3_reg <= tmp_s_reg_238_pp0_iter2_reg;
                tmp_s_reg_238_pp0_iter4_reg <= tmp_s_reg_238_pp0_iter3_reg;
                tmp_s_reg_238_pp0_iter5_reg <= tmp_s_reg_238_pp0_iter4_reg;
                tmp_s_reg_238_pp0_iter6_reg <= tmp_s_reg_238_pp0_iter5_reg;
                tmp_s_reg_238_pp0_iter7_reg <= tmp_s_reg_238_pp0_iter6_reg;
                tmp_s_reg_238_pp0_iter8_reg <= tmp_s_reg_238_pp0_iter7_reg;
                tmp_s_reg_238_pp0_iter9_reg <= tmp_s_reg_238_pp0_iter8_reg;
                trunc_ln78_reg_223_pp0_iter10_reg <= trunc_ln78_reg_223_pp0_iter9_reg;
                trunc_ln78_reg_223_pp0_iter11_reg <= trunc_ln78_reg_223_pp0_iter10_reg;
                trunc_ln78_reg_223_pp0_iter12_reg <= trunc_ln78_reg_223_pp0_iter11_reg;
                trunc_ln78_reg_223_pp0_iter13_reg <= trunc_ln78_reg_223_pp0_iter12_reg;
                trunc_ln78_reg_223_pp0_iter2_reg <= trunc_ln78_reg_223;
                trunc_ln78_reg_223_pp0_iter3_reg <= trunc_ln78_reg_223_pp0_iter2_reg;
                trunc_ln78_reg_223_pp0_iter4_reg <= trunc_ln78_reg_223_pp0_iter3_reg;
                trunc_ln78_reg_223_pp0_iter5_reg <= trunc_ln78_reg_223_pp0_iter4_reg;
                trunc_ln78_reg_223_pp0_iter6_reg <= trunc_ln78_reg_223_pp0_iter5_reg;
                trunc_ln78_reg_223_pp0_iter7_reg <= trunc_ln78_reg_223_pp0_iter6_reg;
                trunc_ln78_reg_223_pp0_iter8_reg <= trunc_ln78_reg_223_pp0_iter7_reg;
                trunc_ln78_reg_223_pp0_iter9_reg <= trunc_ln78_reg_223_pp0_iter8_reg;
                trunc_ln79_1_reg_233_pp0_iter10_reg <= trunc_ln79_1_reg_233_pp0_iter9_reg;
                trunc_ln79_1_reg_233_pp0_iter11_reg <= trunc_ln79_1_reg_233_pp0_iter10_reg;
                trunc_ln79_1_reg_233_pp0_iter12_reg <= trunc_ln79_1_reg_233_pp0_iter11_reg;
                trunc_ln79_1_reg_233_pp0_iter13_reg <= trunc_ln79_1_reg_233_pp0_iter12_reg;
                trunc_ln79_1_reg_233_pp0_iter2_reg <= trunc_ln79_1_reg_233;
                trunc_ln79_1_reg_233_pp0_iter3_reg <= trunc_ln79_1_reg_233_pp0_iter2_reg;
                trunc_ln79_1_reg_233_pp0_iter4_reg <= trunc_ln79_1_reg_233_pp0_iter3_reg;
                trunc_ln79_1_reg_233_pp0_iter5_reg <= trunc_ln79_1_reg_233_pp0_iter4_reg;
                trunc_ln79_1_reg_233_pp0_iter6_reg <= trunc_ln79_1_reg_233_pp0_iter5_reg;
                trunc_ln79_1_reg_233_pp0_iter7_reg <= trunc_ln79_1_reg_233_pp0_iter6_reg;
                trunc_ln79_1_reg_233_pp0_iter8_reg <= trunc_ln79_1_reg_233_pp0_iter7_reg;
                trunc_ln79_1_reg_233_pp0_iter9_reg <= trunc_ln79_1_reg_233_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                p_clouds_addr_reg_212 <= zext_ln76_fu_115_p1(4 - 1 downto 0);
                p_clouds_addr_reg_212_pp0_iter1_reg <= p_clouds_addr_reg_212;
                tmp_s_reg_238 <= p_clouds_q1(223 downto 64);
                trunc_ln3_reg_218 <= p_clouds_q1(159 downto 128);
                trunc_ln4_reg_228 <= p_clouds_q1(191 downto 160);
                trunc_ln78_reg_223 <= trunc_ln78_fu_135_p1;
                trunc_ln79_1_reg_233 <= p_clouds_q1(63 downto 32);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln76_fu_109_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_cloud_1) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln76_fu_103_p2)
    begin
        if (((icmp_ln76_fu_103_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter20_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter20_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21)
    begin
        if (((ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) 
    and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_cloud_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, cloud_fu_56, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_cloud_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_cloud_1 <= cloud_fu_56;
        end if; 
    end process;

    bitcast_ln78_1_fu_177_p1 <= trunc_ln78_reg_223_pp0_iter13_reg;
    bitcast_ln78_2_fu_185_p1 <= add1_reg_273;
    bitcast_ln78_fu_169_p1 <= trunc_ln3_reg_218;
    bitcast_ln79_1_fu_181_p1 <= trunc_ln79_1_reg_233_pp0_iter13_reg;
    bitcast_ln79_2_fu_188_p1 <= add2_reg_278;
    bitcast_ln79_fu_173_p1 <= trunc_ln4_reg_228;
    grp_fu_454_p_ce <= ap_const_logic_1;
    grp_fu_454_p_din0 <= bitcast_ln78_1_fu_177_p1;
    grp_fu_454_p_din1 <= div_reg_253;
    grp_fu_454_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_459_p_ce <= ap_const_logic_1;
    grp_fu_459_p_din0 <= bitcast_ln79_1_fu_181_p1;
    grp_fu_459_p_din1 <= div1_reg_258;
    grp_fu_459_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    grp_fu_485_p_ce <= ap_const_logic_1;
    grp_fu_485_p_din0 <= bitcast_ln78_fu_169_p1;
    grp_fu_485_p_din1 <= ap_const_lv32_42700000;
    grp_fu_490_p_ce <= ap_const_logic_1;
    grp_fu_490_p_din0 <= bitcast_ln79_fu_173_p1;
    grp_fu_490_p_din1 <= ap_const_lv32_42700000;
    icmp_ln76_fu_103_p2 <= "1" when (ap_sig_allocacmp_cloud_1 = ap_const_lv4_9) else "0";
    or_ln_fu_191_p4 <= ((tmp_s_reg_238_pp0_iter20_reg & bitcast_ln79_2_fu_188_p1) & bitcast_ln78_2_fu_185_p1);
    p_clouds_address0 <= p_clouds_addr_reg_212_pp0_iter20_reg;
    p_clouds_address1 <= zext_ln76_fu_115_p1(4 - 1 downto 0);
    p_clouds_ce0 <= p_clouds_ce0_local;

    p_clouds_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter21, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter21 = ap_const_logic_1))) then 
            p_clouds_ce0_local <= ap_const_logic_1;
        else 
            p_clouds_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_clouds_ce1 <= p_clouds_ce1_local;

    p_clouds_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_clouds_ce1_local <= ap_const_logic_1;
        else 
            p_clouds_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_clouds_d0 <= or_ln_fu_191_p4;
    p_clouds_we0 <= p_clouds_we0_local;

    p_clouds_we0_local_assign_proc : process(ap_enable_reg_pp0_iter21, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter21 = ap_const_logic_1))) then 
            p_clouds_we0_local <= ap_const_logic_1;
        else 
            p_clouds_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln78_fu_135_p1 <= p_clouds_q1(32 - 1 downto 0);
    zext_ln76_fu_115_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_cloud_1),64));
end behav;
