-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity do_compute_do_compute_Pipeline_VITIS_LOOP_249_16_VITIS_LOOP_250_17 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    trunc_ln2 : IN STD_LOGIC_VECTOR (63 downto 0);
    water_level_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    water_level_ce0 : OUT STD_LOGIC;
    water_level_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    water_level_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    water_level_1_ce0 : OUT STD_LOGIC;
    water_level_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    water_level_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    water_level_2_ce0 : OUT STD_LOGIC;
    water_level_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out_ap_vld : OUT STD_LOGIC;
    add55123_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    add55123_out_ap_vld : OUT STD_LOGIC;
    grp_fu_481_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_481_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_481_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_481_p_ce : OUT STD_LOGIC;
    grp_fu_1441_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1441_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1441_p_ce : OUT STD_LOGIC;
    grp_fu_503_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_503_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_503_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_503_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_503_p_ce : OUT STD_LOGIC );
end;


architecture behav of do_compute_do_compute_Pipeline_VITIS_LOOP_249_16_VITIS_LOOP_250_17 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_49742400 : STD_LOGIC_VECTOR (31 downto 0) := "01001001011101000010010000000000";
    constant ap_const_lv12_9C4 : STD_LOGIC_VECTOR (11 downto 0) := "100111000100";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv6_32 : STD_LOGIC_VECTOR (5 downto 0) := "110010";
    constant ap_const_lv6_3 : STD_LOGIC_VECTOR (5 downto 0) := "000011";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv13_56 : STD_LOGIC_VECTOR (12 downto 0) := "0000001010110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln249_reg_512 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln249_fu_207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_512_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_512_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_512_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_512_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_512_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_512_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_512_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_512_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_512_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_512_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_512_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_512_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln250_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln250_reg_516 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_fu_228_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln52_reg_521 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln251_fu_315_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln251_reg_527 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal water_level_load_reg_547 : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_load_reg_547_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_load_reg_547_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_1_load_reg_552 : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_1_load_reg_552_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_1_load_reg_552_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_2_load_reg_557 : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_2_load_reg_557_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_2_load_reg_557_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_336_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_562 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv1_reg_568 : STD_LOGIC_VECTOR (31 downto 0);
    signal div6_reg_573 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_load11_reg_580 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal zext_ln251_1_fu_326_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal add55123_fu_88 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln253_fu_359_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal empty_fu_92 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln251_fu_456_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal col_pos_1_fu_96 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln250_fu_242_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_col_pos_1_load : STD_LOGIC_VECTOR (5 downto 0);
    signal row_pos_fu_100 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln249_fu_267_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten34_fu_104 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal add_ln249_1_fu_213_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_indvar_flatten34_load : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal water_level_ce0_local : STD_LOGIC;
    signal water_level_1_ce0_local : STD_LOGIC;
    signal water_level_2_ce0_local : STD_LOGIC;
    signal grp_fu_236_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln249_fu_261_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_34_fu_278_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln52_fu_274_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln52_fu_295_p0 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln52_fu_295_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln52_fu_295_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_35_fu_301_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln52_fu_286_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln251_fu_311_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_236_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_336_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_336_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln253_fu_356_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln251_fu_374_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln251_1_fu_391_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_377_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln251_fu_387_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln251_1_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln251_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_394_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln251_1_fu_404_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln251_3_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln251_2_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln251_1_fu_438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln251_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln251_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln251_1_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to13 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln52_fu_295_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_fu_336_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_336_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_336_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component do_compute_fdiv_32ns_32ns_32_12_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component do_compute_sitofp_32s_32_4_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component do_compute_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component do_compute_urem_6ns_3ns_2_10_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component do_compute_mul_6ns_8ns_13_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component do_compute_sparsemux_7_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component do_compute_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    urem_6ns_3ns_2_10_1_U188 : component do_compute_urem_6ns_3ns_2_10_1
    generic map (
        ID => 1,
        NUM_STAGE => 10,
        din0_WIDTH => 6,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln52_fu_228_p3,
        din1 => grp_fu_236_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_236_p2);

    mul_6ns_8ns_13_1_1_U189 : component do_compute_mul_6ns_8ns_13_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 6,
        din1_WIDTH => 8,
        dout_WIDTH => 13)
    port map (
        din0 => mul_ln52_fu_295_p0,
        din1 => mul_ln52_fu_295_p1,
        dout => mul_ln52_fu_295_p2);

    sparsemux_7_2_32_1_1_U190 : component do_compute_sparsemux_7_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => water_level_load_reg_547_pp0_iter3_reg,
        din1 => water_level_1_load_reg_552_pp0_iter3_reg,
        din2 => water_level_2_load_reg_557_pp0_iter3_reg,
        def => tmp_fu_336_p7,
        sel => tmp_fu_336_p8,
        dout => tmp_fu_336_p9);

    flow_control_loop_pipe_sequential_init_U : component do_compute_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    add55123_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    add55123_fu_88 <= trunc_ln2;
                elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                    add55123_fu_88 <= add_ln253_fu_359_p2;
                end if;
            end if; 
        end if;
    end process;

    col_pos_1_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln249_fu_207_p2 = ap_const_lv1_0))) then 
                    col_pos_1_fu_96 <= add_ln250_fu_242_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    col_pos_1_fu_96 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    empty_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                empty_fu_92 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                empty_fu_92 <= select_ln251_fu_456_p3;
            end if; 
        end if;
    end process;

    indvar_flatten34_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln249_fu_207_p2 = ap_const_lv1_0))) then 
                    indvar_flatten34_fu_104 <= add_ln249_1_fu_213_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten34_fu_104 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;

    row_pos_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                row_pos_fu_100 <= ap_const_lv6_0;
            elsif (((icmp_ln249_reg_512 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                row_pos_fu_100 <= select_ln249_fu_267_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln251_reg_527 <= add_ln251_fu_315_p2;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                conv1_reg_568 <= grp_fu_1441_p_dout0;
                div6_reg_573 <= grp_fu_481_p_dout0;
                tmp_reg_562 <= tmp_fu_336_p9;
                water_level_1_load_reg_552 <= water_level_1_q0;
                water_level_1_load_reg_552_pp0_iter2_reg <= water_level_1_load_reg_552;
                water_level_1_load_reg_552_pp0_iter3_reg <= water_level_1_load_reg_552_pp0_iter2_reg;
                water_level_2_load_reg_557 <= water_level_2_q0;
                water_level_2_load_reg_557_pp0_iter2_reg <= water_level_2_load_reg_557;
                water_level_2_load_reg_557_pp0_iter3_reg <= water_level_2_load_reg_557_pp0_iter2_reg;
                water_level_load_reg_547 <= water_level_q0;
                water_level_load_reg_547_pp0_iter2_reg <= water_level_load_reg_547;
                water_level_load_reg_547_pp0_iter3_reg <= water_level_load_reg_547_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln249_reg_512 <= icmp_ln249_fu_207_p2;
                icmp_ln249_reg_512_pp0_iter10_reg <= icmp_ln249_reg_512_pp0_iter9_reg;
                icmp_ln249_reg_512_pp0_iter11_reg <= icmp_ln249_reg_512_pp0_iter10_reg;
                icmp_ln249_reg_512_pp0_iter12_reg <= icmp_ln249_reg_512_pp0_iter11_reg;
                icmp_ln249_reg_512_pp0_iter1_reg <= icmp_ln249_reg_512;
                icmp_ln249_reg_512_pp0_iter2_reg <= icmp_ln249_reg_512_pp0_iter1_reg;
                icmp_ln249_reg_512_pp0_iter3_reg <= icmp_ln249_reg_512_pp0_iter2_reg;
                icmp_ln249_reg_512_pp0_iter4_reg <= icmp_ln249_reg_512_pp0_iter3_reg;
                icmp_ln249_reg_512_pp0_iter5_reg <= icmp_ln249_reg_512_pp0_iter4_reg;
                icmp_ln249_reg_512_pp0_iter6_reg <= icmp_ln249_reg_512_pp0_iter5_reg;
                icmp_ln249_reg_512_pp0_iter7_reg <= icmp_ln249_reg_512_pp0_iter6_reg;
                icmp_ln249_reg_512_pp0_iter8_reg <= icmp_ln249_reg_512_pp0_iter7_reg;
                icmp_ln249_reg_512_pp0_iter9_reg <= icmp_ln249_reg_512_pp0_iter8_reg;
                icmp_ln250_reg_516 <= icmp_ln250_fu_222_p2;
                p_load11_reg_580 <= empty_fu_92;
                select_ln52_reg_521 <= select_ln52_fu_228_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to13, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to13 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add55123_out <= add55123_fu_88;

    add55123_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln249_reg_512_pp0_iter12_reg, ap_block_pp0_stage1_11001, ap_loop_exit_ready_pp0_iter12_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln249_reg_512_pp0_iter12_reg = ap_const_lv1_1))) then 
            add55123_out_ap_vld <= ap_const_logic_1;
        else 
            add55123_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln249_1_fu_213_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten34_load) + unsigned(ap_const_lv12_1));
    add_ln249_fu_261_p2 <= std_logic_vector(unsigned(row_pos_fu_100) + unsigned(ap_const_lv6_1));
    add_ln250_fu_242_p2 <= std_logic_vector(unsigned(select_ln52_fu_228_p3) + unsigned(ap_const_lv6_1));
    add_ln251_fu_315_p2 <= std_logic_vector(unsigned(add_ln52_fu_286_p2) + unsigned(zext_ln251_fu_311_p1));
    add_ln253_fu_359_p2 <= std_logic_vector(signed(sext_ln253_fu_356_p1) + signed(add55123_fu_88));
    add_ln52_fu_286_p2 <= std_logic_vector(unsigned(tmp_34_fu_278_p3) + unsigned(zext_ln52_fu_274_p1));
    and_ln251_1_fu_450_p2 <= (grp_fu_503_p_dout0 and and_ln251_fu_444_p2);
    and_ln251_fu_444_p2 <= (or_ln251_fu_420_p2 and or_ln251_1_fu_438_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln249_reg_512)
    begin
        if (((icmp_ln249_reg_512 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready_pp0_iter12_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to13_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to13 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to13 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_col_pos_1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, col_pos_1_fu_96)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_col_pos_1_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_col_pos_1_load <= col_pos_1_fu_96;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten34_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten34_fu_104)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten34_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_indvar_flatten34_load <= indvar_flatten34_fu_104;
        end if; 
    end process;

    bitcast_ln251_1_fu_391_p1 <= p_load11_reg_580;
    bitcast_ln251_fu_374_p1 <= div6_reg_573;
    grp_fu_1441_p_ce <= ap_const_logic_1;
    grp_fu_1441_p_din0 <= tmp_reg_562;
    grp_fu_236_p1 <= ap_const_lv6_3(3 - 1 downto 0);
    grp_fu_481_p_ce <= ap_const_logic_1;
    grp_fu_481_p_din0 <= conv1_reg_568;
    grp_fu_481_p_din1 <= ap_const_lv32_49742400;
    grp_fu_503_p_ce <= ap_const_logic_1;
    grp_fu_503_p_din0 <= div6_reg_573;
    grp_fu_503_p_din1 <= empty_fu_92;
    grp_fu_503_p_opcode <= ap_const_lv5_2;
    icmp_ln249_fu_207_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten34_load = ap_const_lv12_9C4) else "0";
    icmp_ln250_fu_222_p2 <= "1" when (ap_sig_allocacmp_col_pos_1_load = ap_const_lv6_32) else "0";
    icmp_ln251_1_fu_414_p2 <= "1" when (trunc_ln251_fu_387_p1 = ap_const_lv23_0) else "0";
    icmp_ln251_2_fu_426_p2 <= "0" when (tmp_24_fu_394_p4 = ap_const_lv8_FF) else "1";
    icmp_ln251_3_fu_432_p2 <= "1" when (trunc_ln251_1_fu_404_p1 = ap_const_lv23_0) else "0";
    icmp_ln251_fu_408_p2 <= "0" when (tmp_10_fu_377_p4 = ap_const_lv8_FF) else "1";
    mul_ln52_fu_295_p0 <= mul_ln52_fu_295_p00(6 - 1 downto 0);
    mul_ln52_fu_295_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln52_reg_521),13));
    mul_ln52_fu_295_p1 <= ap_const_lv13_56(8 - 1 downto 0);
    or_ln251_1_fu_438_p2 <= (icmp_ln251_3_fu_432_p2 or icmp_ln251_2_fu_426_p2);
    or_ln251_fu_420_p2 <= (icmp_ln251_fu_408_p2 or icmp_ln251_1_fu_414_p2);
    p_out <= empty_fu_92;

    p_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln249_reg_512_pp0_iter12_reg, ap_block_pp0_stage1_11001, ap_loop_exit_ready_pp0_iter12_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln249_reg_512_pp0_iter12_reg = ap_const_lv1_1))) then 
            p_out_ap_vld <= ap_const_logic_1;
        else 
            p_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln249_fu_267_p3 <= 
        add_ln249_fu_261_p2 when (icmp_ln250_reg_516(0) = '1') else 
        row_pos_fu_100;
    select_ln251_fu_456_p3 <= 
        div6_reg_573 when (and_ln251_1_fu_450_p2(0) = '1') else 
        p_load11_reg_580;
    select_ln52_fu_228_p3 <= 
        ap_const_lv6_0 when (icmp_ln250_fu_222_p2(0) = '1') else 
        ap_sig_allocacmp_col_pos_1_load;
        sext_ln253_fu_356_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_reg_562),64));

    tmp_10_fu_377_p4 <= bitcast_ln251_fu_374_p1(30 downto 23);
    tmp_24_fu_394_p4 <= bitcast_ln251_1_fu_391_p1(30 downto 23);
    tmp_34_fu_278_p3 <= (select_ln249_fu_267_p3 & ap_const_lv4_0);
    tmp_35_fu_301_p4 <= mul_ln52_fu_295_p2(12 downto 8);
    tmp_fu_336_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_fu_336_p8 <= grp_fu_236_p2(2 - 1 downto 0);
    trunc_ln251_1_fu_404_p1 <= bitcast_ln251_1_fu_391_p1(23 - 1 downto 0);
    trunc_ln251_fu_387_p1 <= bitcast_ln251_fu_374_p1(23 - 1 downto 0);
    water_level_1_address0 <= zext_ln251_1_fu_326_p1(10 - 1 downto 0);
    water_level_1_ce0 <= water_level_1_ce0_local;

    water_level_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            water_level_1_ce0_local <= ap_const_logic_1;
        else 
            water_level_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    water_level_2_address0 <= zext_ln251_1_fu_326_p1(10 - 1 downto 0);
    water_level_2_ce0 <= water_level_2_ce0_local;

    water_level_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            water_level_2_ce0_local <= ap_const_logic_1;
        else 
            water_level_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    water_level_address0 <= zext_ln251_1_fu_326_p1(10 - 1 downto 0);
    water_level_ce0 <= water_level_ce0_local;

    water_level_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            water_level_ce0_local <= ap_const_logic_1;
        else 
            water_level_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln251_1_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln251_reg_527),64));
    zext_ln251_fu_311_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_35_fu_301_p4),10));
    zext_ln52_fu_274_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln249_fu_267_p3),10));
end behav;
