-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity do_compute_do_compute_Pipeline_VITIS_LOOP_234_13_VITIS_LOOP_235_14 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    spillage_flag_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    spillage_flag_ce0 : OUT STD_LOGIC;
    spillage_flag_we0 : OUT STD_LOGIC;
    spillage_flag_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    spillage_level_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    spillage_level_ce0 : OUT STD_LOGIC;
    spillage_level_we0 : OUT STD_LOGIC;
    spillage_level_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    spillage_from_neigh_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    spillage_from_neigh_ce0 : OUT STD_LOGIC;
    spillage_from_neigh_we0 : OUT STD_LOGIC;
    spillage_from_neigh_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    spillage_from_neigh_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    spillage_from_neigh_1_ce0 : OUT STD_LOGIC;
    spillage_from_neigh_1_we0 : OUT STD_LOGIC;
    spillage_from_neigh_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    spillage_from_neigh_2_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    spillage_from_neigh_2_ce0 : OUT STD_LOGIC;
    spillage_from_neigh_2_we0 : OUT STD_LOGIC;
    spillage_from_neigh_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    spillage_from_neigh_3_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    spillage_from_neigh_3_ce0 : OUT STD_LOGIC;
    spillage_from_neigh_3_we0 : OUT STD_LOGIC;
    spillage_from_neigh_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of do_compute_do_compute_Pipeline_VITIS_LOOP_234_13_VITIS_LOOP_235_14 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv13_1FA4 : STD_LOGIC_VECTOR (12 downto 0) := "1111110100100";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_5A : STD_LOGIC_VECTOR (6 downto 0) := "1011010";
    constant ap_const_lv13_5A : STD_LOGIC_VECTOR (12 downto 0) := "0000001011010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln234_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln52_fu_192_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln52_reg_279 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln52_reg_279_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln241_1_fu_236_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal col_pos_fu_48 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln235_fu_212_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_col_pos_load : STD_LOGIC_VECTOR (6 downto 0);
    signal row_pos_fu_52 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln234_fu_200_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_row_pos_load : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten25_fu_56 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal add_ln234_1_fu_168_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_sig_allocacmp_indvar_flatten25_load : STD_LOGIC_VECTOR (12 downto 0);
    signal spillage_from_neigh_we0_local : STD_LOGIC;
    signal spillage_from_neigh_ce0_local : STD_LOGIC;
    signal spillage_from_neigh_1_we0_local : STD_LOGIC;
    signal spillage_from_neigh_1_ce0_local : STD_LOGIC;
    signal spillage_from_neigh_2_we0_local : STD_LOGIC;
    signal spillage_from_neigh_2_ce0_local : STD_LOGIC;
    signal spillage_from_neigh_3_we0_local : STD_LOGIC;
    signal spillage_from_neigh_3_ce0_local : STD_LOGIC;
    signal spillage_flag_we0_local : STD_LOGIC;
    signal spillage_flag_ce0_local : STD_LOGIC;
    signal spillage_level_we0_local : STD_LOGIC;
    signal spillage_level_ce0_local : STD_LOGIC;
    signal icmp_ln235_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln234_fu_180_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_245_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_245_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_245_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_245_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_245_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_245_p20 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component do_compute_mac_muladd_7ns_7ns_7ns_13_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component do_compute_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_7ns_7ns_7ns_13_4_1_U177 : component do_compute_mac_muladd_7ns_7ns_7ns_13_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 7,
        din1_WIDTH => 7,
        din2_WIDTH => 7,
        dout_WIDTH => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_245_p0,
        din1 => grp_fu_245_p1,
        din2 => grp_fu_245_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_245_p3);

    flow_control_loop_pipe_sequential_init_U : component do_compute_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    col_pos_fu_48_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln234_fu_162_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    col_pos_fu_48 <= add_ln235_fu_212_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    col_pos_fu_48 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten25_fu_56_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln234_fu_162_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten25_fu_56 <= add_ln234_1_fu_168_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten25_fu_56 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    row_pos_fu_52_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln234_fu_162_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    row_pos_fu_52 <= select_ln234_fu_200_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    row_pos_fu_52 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                select_ln52_reg_279 <= select_ln52_fu_192_p3;
                select_ln52_reg_279_pp0_iter1_reg <= select_ln52_reg_279;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln234_1_fu_168_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten25_load) + unsigned(ap_const_lv13_1));
    add_ln234_fu_180_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_row_pos_load) + unsigned(ap_const_lv7_1));
    add_ln235_fu_212_p2 <= std_logic_vector(unsigned(select_ln52_fu_192_p3) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln234_fu_162_p2)
    begin
        if (((icmp_ln234_fu_162_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_col_pos_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, col_pos_fu_48, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_col_pos_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_col_pos_load <= col_pos_fu_48;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten25_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten25_fu_56)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten25_load <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_indvar_flatten25_load <= indvar_flatten25_fu_56;
        end if; 
    end process;


    ap_sig_allocacmp_row_pos_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, row_pos_fu_52)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_row_pos_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_row_pos_load <= row_pos_fu_52;
        end if; 
    end process;

    grp_fu_245_p0 <= grp_fu_245_p00(7 - 1 downto 0);
    grp_fu_245_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln234_fu_200_p3),13));
    grp_fu_245_p1 <= ap_const_lv13_5A(7 - 1 downto 0);
    grp_fu_245_p2 <= grp_fu_245_p20(7 - 1 downto 0);
    grp_fu_245_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln52_reg_279_pp0_iter1_reg),13));
    icmp_ln234_fu_162_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten25_load = ap_const_lv13_1FA4) else "0";
    icmp_ln235_fu_186_p2 <= "1" when (ap_sig_allocacmp_col_pos_load = ap_const_lv7_5A) else "0";
    select_ln234_fu_200_p3 <= 
        add_ln234_fu_180_p2 when (icmp_ln235_fu_186_p2(0) = '1') else 
        ap_sig_allocacmp_row_pos_load;
    select_ln52_fu_192_p3 <= 
        ap_const_lv7_0 when (icmp_ln235_fu_186_p2(0) = '1') else 
        ap_sig_allocacmp_col_pos_load;
    spillage_flag_address0 <= zext_ln241_1_fu_236_p1(13 - 1 downto 0);
    spillage_flag_ce0 <= spillage_flag_ce0_local;

    spillage_flag_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_flag_ce0_local <= ap_const_logic_1;
        else 
            spillage_flag_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_flag_d0 <= ap_const_lv32_0;
    spillage_flag_we0 <= spillage_flag_we0_local;

    spillage_flag_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_flag_we0_local <= ap_const_logic_1;
        else 
            spillage_flag_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_1_address0 <= zext_ln241_1_fu_236_p1(13 - 1 downto 0);
    spillage_from_neigh_1_ce0 <= spillage_from_neigh_1_ce0_local;

    spillage_from_neigh_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_1_ce0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_1_d0 <= ap_const_lv32_0;
    spillage_from_neigh_1_we0 <= spillage_from_neigh_1_we0_local;

    spillage_from_neigh_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_1_we0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_2_address0 <= zext_ln241_1_fu_236_p1(13 - 1 downto 0);
    spillage_from_neigh_2_ce0 <= spillage_from_neigh_2_ce0_local;

    spillage_from_neigh_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_2_ce0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_2_d0 <= ap_const_lv32_0;
    spillage_from_neigh_2_we0 <= spillage_from_neigh_2_we0_local;

    spillage_from_neigh_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_2_we0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_3_address0 <= zext_ln241_1_fu_236_p1(13 - 1 downto 0);
    spillage_from_neigh_3_ce0 <= spillage_from_neigh_3_ce0_local;

    spillage_from_neigh_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_3_ce0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_3_d0 <= ap_const_lv32_0;
    spillage_from_neigh_3_we0 <= spillage_from_neigh_3_we0_local;

    spillage_from_neigh_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_3_we0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_address0 <= zext_ln241_1_fu_236_p1(13 - 1 downto 0);
    spillage_from_neigh_ce0 <= spillage_from_neigh_ce0_local;

    spillage_from_neigh_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_ce0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_from_neigh_d0 <= ap_const_lv32_0;
    spillage_from_neigh_we0 <= spillage_from_neigh_we0_local;

    spillage_from_neigh_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_from_neigh_we0_local <= ap_const_logic_1;
        else 
            spillage_from_neigh_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_level_address0 <= zext_ln241_1_fu_236_p1(13 - 1 downto 0);
    spillage_level_ce0 <= spillage_level_ce0_local;

    spillage_level_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_level_ce0_local <= ap_const_logic_1;
        else 
            spillage_level_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    spillage_level_d0 <= ap_const_lv32_0;
    spillage_level_we0 <= spillage_level_we0_local;

    spillage_level_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spillage_level_we0_local <= ap_const_logic_1;
        else 
            spillage_level_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln241_1_fu_236_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_245_p3),64));
end behav;
