-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity do_compute_do_compute_Pipeline_VITIS_LOOP_249_16_VITIS_LOOP_250_17 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    trunc_ln2 : IN STD_LOGIC_VECTOR (63 downto 0);
    water_level_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    water_level_ce0 : OUT STD_LOGIC;
    water_level_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    water_level_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    water_level_1_ce0 : OUT STD_LOGIC;
    water_level_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    water_level_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    water_level_2_ce0 : OUT STD_LOGIC;
    water_level_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out_ap_vld : OUT STD_LOGIC;
    add55123_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    add55123_out_ap_vld : OUT STD_LOGIC;
    grp_fu_485_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_485_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_485_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_485_p_ce : OUT STD_LOGIC;
    grp_fu_1445_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1445_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1445_p_ce : OUT STD_LOGIC;
    grp_fu_507_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_507_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_507_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_507_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_507_p_ce : OUT STD_LOGIC );
end;


architecture behav of do_compute_do_compute_Pipeline_VITIS_LOOP_249_16_VITIS_LOOP_250_17 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_49742400 : STD_LOGIC_VECTOR (31 downto 0) := "01001001011101000010010000000000";
    constant ap_const_lv13_12C0 : STD_LOGIC_VECTOR (12 downto 0) := "1001011000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv7_50 : STD_LOGIC_VECTOR (6 downto 0) := "1010000";
    constant ap_const_lv15_AB : STD_LOGIC_VECTOR (14 downto 0) := "000000010101011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv7_3 : STD_LOGIC_VECTOR (6 downto 0) := "0000011";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv11_1B : STD_LOGIC_VECTOR (10 downto 0) := "00000011011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln249_reg_504 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln249_fu_209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_504_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_504_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_504_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_504_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_504_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_504_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_504_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_504_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_504_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_504_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_504_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln249_reg_504_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_fu_239_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_35_reg_518 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal water_level_load_reg_543 : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_load_reg_543_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_load_reg_543_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_1_load_reg_548 : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_1_load_reg_548_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_1_load_reg_548_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_2_load_reg_553 : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_2_load_reg_553_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal water_level_2_load_reg_553_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_319_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_558 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv1_reg_564 : STD_LOGIC_VECTOR (31 downto 0);
    signal div6_reg_569 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_load10_reg_576 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln251_2_fu_309_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal add55123_fu_90 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln253_fu_342_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter13_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to12 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal empty_fu_94 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal select_ln251_fu_439_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal col_pos_1_fu_98 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln250_fu_285_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_col_pos_1_load : STD_LOGIC_VECTOR (6 downto 0);
    signal row_pos_fu_102 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln249_fu_247_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_row_pos_load : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten34_fu_106 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal add_ln249_1_fu_215_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_sig_allocacmp_indvar_flatten34_load : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal water_level_ce0_local : STD_LOGIC;
    signal water_level_1_ce0_local : STD_LOGIC;
    signal water_level_2_ce0_local : STD_LOGIC;
    signal icmp_ln250_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln249_fu_227_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln52_fu_263_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln52_fu_263_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln52_fu_263_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_279_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_458_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_279_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_319_p7 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_319_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln253_fu_339_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln251_fu_357_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln251_1_fu_374_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_360_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln251_fu_370_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln251_1_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln251_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_377_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln251_1_fu_387_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln251_3_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln251_2_fu_409_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln251_1_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln251_fu_403_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln251_fu_427_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln251_1_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_458_p0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_458_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_458_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage1_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to14 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_458_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_458_p20 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln52_fu_263_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_fu_319_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_319_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_319_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component do_compute_fdiv_32ns_32ns_32_12_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component do_compute_sitofp_32s_32_4_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component do_compute_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component do_compute_mul_7ns_9ns_15_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component do_compute_urem_7ns_3ns_2_11_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component do_compute_sparsemux_7_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component do_compute_mac_muladd_6ns_5ns_6ns_11_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (5 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component do_compute_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_7ns_9ns_15_1_1_U188 : component do_compute_mul_7ns_9ns_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 7,
        din1_WIDTH => 9,
        dout_WIDTH => 15)
    port map (
        din0 => mul_ln52_fu_263_p0,
        din1 => mul_ln52_fu_263_p1,
        dout => mul_ln52_fu_263_p2);

    urem_7ns_3ns_2_11_1_U189 : component do_compute_urem_7ns_3ns_2_11_1
    generic map (
        ID => 1,
        NUM_STAGE => 11,
        din0_WIDTH => 7,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln52_fu_239_p3,
        din1 => grp_fu_279_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_279_p2);

    sparsemux_7_2_32_1_1_U190 : component do_compute_sparsemux_7_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => water_level_load_reg_543_pp0_iter4_reg,
        din1 => water_level_1_load_reg_548_pp0_iter4_reg,
        din2 => water_level_2_load_reg_553_pp0_iter4_reg,
        def => tmp_fu_319_p7,
        sel => tmp_fu_319_p8,
        dout => tmp_fu_319_p9);

    mac_muladd_6ns_5ns_6ns_11_4_1_U191 : component do_compute_mac_muladd_6ns_5ns_6ns_11_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 6,
        din1_WIDTH => 5,
        din2_WIDTH => 6,
        dout_WIDTH => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_458_p0,
        din1 => grp_fu_458_p1,
        din2 => grp_fu_458_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_458_p3);

    flow_control_loop_pipe_sequential_init_U : component do_compute_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    add55123_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                add55123_fu_90 <= trunc_ln2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                add55123_fu_90 <= add_ln253_fu_342_p2;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter10_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to12 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter13_stage0))) then 
                ap_loop_exit_ready_pp0_iter10_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter11_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to12 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter13_stage0))) then 
                ap_loop_exit_ready_pp0_iter11_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter12_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to12 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter13_stage0))) then 
                ap_loop_exit_ready_pp0_iter12_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter13_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to12 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter13_stage0))) then 
                ap_loop_exit_ready_pp0_iter13_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to12 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter13_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to12 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter13_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to12 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter13_stage0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter4_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to12 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter13_stage0))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter5_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to12 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter13_stage0))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter6_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to12 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter13_stage0))) then 
                ap_loop_exit_ready_pp0_iter6_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter7_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to12 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter13_stage0))) then 
                ap_loop_exit_ready_pp0_iter7_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter8_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to12 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter13_stage0))) then 
                ap_loop_exit_ready_pp0_iter8_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter9_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to12 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter13_stage0))) then 
                ap_loop_exit_ready_pp0_iter9_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
            end if; 
        end if;
    end process;

    col_pos_1_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln249_fu_209_p2 = ap_const_lv1_0))) then 
                    col_pos_1_fu_98 <= add_ln250_fu_285_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    col_pos_1_fu_98 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    empty_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_fu_94 <= ap_const_lv32_0;
                elsif ((ap_enable_reg_pp0_iter14 = ap_const_logic_1)) then 
                    empty_fu_94 <= select_ln251_fu_439_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten34_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln249_fu_209_p2 = ap_const_lv1_0))) then 
                    indvar_flatten34_fu_106 <= add_ln249_1_fu_215_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten34_fu_106 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    row_pos_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln249_fu_209_p2 = ap_const_lv1_0))) then 
                    row_pos_fu_102 <= select_ln249_fu_247_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    row_pos_fu_102 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                conv1_reg_564 <= grp_fu_1445_p_dout0;
                div6_reg_569 <= grp_fu_485_p_dout0;
                icmp_ln249_reg_504 <= icmp_ln249_fu_209_p2;
                icmp_ln249_reg_504_pp0_iter10_reg <= icmp_ln249_reg_504_pp0_iter9_reg;
                icmp_ln249_reg_504_pp0_iter11_reg <= icmp_ln249_reg_504_pp0_iter10_reg;
                icmp_ln249_reg_504_pp0_iter12_reg <= icmp_ln249_reg_504_pp0_iter11_reg;
                icmp_ln249_reg_504_pp0_iter1_reg <= icmp_ln249_reg_504;
                icmp_ln249_reg_504_pp0_iter2_reg <= icmp_ln249_reg_504_pp0_iter1_reg;
                icmp_ln249_reg_504_pp0_iter3_reg <= icmp_ln249_reg_504_pp0_iter2_reg;
                icmp_ln249_reg_504_pp0_iter4_reg <= icmp_ln249_reg_504_pp0_iter3_reg;
                icmp_ln249_reg_504_pp0_iter5_reg <= icmp_ln249_reg_504_pp0_iter4_reg;
                icmp_ln249_reg_504_pp0_iter6_reg <= icmp_ln249_reg_504_pp0_iter5_reg;
                icmp_ln249_reg_504_pp0_iter7_reg <= icmp_ln249_reg_504_pp0_iter6_reg;
                icmp_ln249_reg_504_pp0_iter8_reg <= icmp_ln249_reg_504_pp0_iter7_reg;
                icmp_ln249_reg_504_pp0_iter9_reg <= icmp_ln249_reg_504_pp0_iter8_reg;
                tmp_35_reg_518 <= mul_ln52_fu_263_p2(14 downto 9);
                tmp_reg_558 <= tmp_fu_319_p9;
                water_level_1_load_reg_548 <= water_level_1_q0;
                water_level_1_load_reg_548_pp0_iter3_reg <= water_level_1_load_reg_548;
                water_level_1_load_reg_548_pp0_iter4_reg <= water_level_1_load_reg_548_pp0_iter3_reg;
                water_level_2_load_reg_553 <= water_level_2_q0;
                water_level_2_load_reg_553_pp0_iter3_reg <= water_level_2_load_reg_553;
                water_level_2_load_reg_553_pp0_iter4_reg <= water_level_2_load_reg_553_pp0_iter3_reg;
                water_level_load_reg_543 <= water_level_q0;
                water_level_load_reg_543_pp0_iter3_reg <= water_level_load_reg_543;
                water_level_load_reg_543_pp0_iter4_reg <= water_level_load_reg_543_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_load10_reg_576 <= empty_fu_94;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter13_stage0, ap_idle_pp0_0to12, ap_idle_pp0_1to14, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to12 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter13_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to14 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add55123_out <= add55123_fu_90;

    add55123_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln249_reg_504_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln249_reg_504_pp0_iter12_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            add55123_out_ap_vld <= ap_const_logic_1;
        else 
            add55123_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln249_1_fu_215_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten34_load) + unsigned(ap_const_lv13_1));
    add_ln249_fu_227_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_row_pos_load) + unsigned(ap_const_lv6_1));
    add_ln250_fu_285_p2 <= std_logic_vector(unsigned(select_ln52_fu_239_p3) + unsigned(ap_const_lv7_1));
    add_ln253_fu_342_p2 <= std_logic_vector(signed(sext_ln253_fu_339_p1) + signed(add55123_fu_90));
    and_ln251_1_fu_433_p2 <= (grp_fu_507_p_dout0 and and_ln251_fu_427_p2);
    and_ln251_fu_427_p2 <= (or_ln251_fu_403_p2 and or_ln251_1_fu_421_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln249_reg_504)
    begin
        if (((icmp_ln249_reg_504 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter13_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter13, icmp_ln249_reg_504_pp0_iter12_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (icmp_ln249_reg_504_pp0_iter12_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter13_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter13_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter13_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to12_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to12 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to12 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to14_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to14 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to14 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_col_pos_1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, col_pos_1_fu_98)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_col_pos_1_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_col_pos_1_load <= col_pos_1_fu_98;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten34_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten34_fu_106)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten34_load <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_indvar_flatten34_load <= indvar_flatten34_fu_106;
        end if; 
    end process;


    ap_sig_allocacmp_row_pos_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, row_pos_fu_102)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_row_pos_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_row_pos_load <= row_pos_fu_102;
        end if; 
    end process;

    bitcast_ln251_1_fu_374_p1 <= p_load10_reg_576;
    bitcast_ln251_fu_357_p1 <= div6_reg_569;
    grp_fu_1445_p_ce <= ap_const_logic_1;
    grp_fu_1445_p_din0 <= tmp_reg_558;
    grp_fu_279_p1 <= ap_const_lv7_3(3 - 1 downto 0);
    grp_fu_458_p0 <= grp_fu_458_p00(6 - 1 downto 0);
    grp_fu_458_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln249_fu_247_p3),11));
    grp_fu_458_p1 <= ap_const_lv11_1B(5 - 1 downto 0);
    grp_fu_458_p2 <= grp_fu_458_p20(6 - 1 downto 0);
    grp_fu_458_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_35_reg_518),11));
    grp_fu_485_p_ce <= ap_const_logic_1;
    grp_fu_485_p_din0 <= conv1_reg_564;
    grp_fu_485_p_din1 <= ap_const_lv32_49742400;
    grp_fu_507_p_ce <= ap_const_logic_1;
    grp_fu_507_p_din0 <= div6_reg_569;
    grp_fu_507_p_din1 <= empty_fu_94;
    grp_fu_507_p_opcode <= ap_const_lv5_2;
    icmp_ln249_fu_209_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten34_load = ap_const_lv13_12C0) else "0";
    icmp_ln250_fu_233_p2 <= "1" when (ap_sig_allocacmp_col_pos_1_load = ap_const_lv7_50) else "0";
    icmp_ln251_1_fu_397_p2 <= "1" when (trunc_ln251_fu_370_p1 = ap_const_lv23_0) else "0";
    icmp_ln251_2_fu_409_p2 <= "0" when (tmp_24_fu_377_p4 = ap_const_lv8_FF) else "1";
    icmp_ln251_3_fu_415_p2 <= "1" when (trunc_ln251_1_fu_387_p1 = ap_const_lv23_0) else "0";
    icmp_ln251_fu_391_p2 <= "0" when (tmp_10_fu_360_p4 = ap_const_lv8_FF) else "1";
    mul_ln52_fu_263_p0 <= mul_ln52_fu_263_p00(7 - 1 downto 0);
    mul_ln52_fu_263_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln52_fu_239_p3),15));
    mul_ln52_fu_263_p1 <= ap_const_lv15_AB(9 - 1 downto 0);
    or_ln251_1_fu_421_p2 <= (icmp_ln251_3_fu_415_p2 or icmp_ln251_2_fu_409_p2);
    or_ln251_fu_403_p2 <= (icmp_ln251_fu_391_p2 or icmp_ln251_1_fu_397_p2);
    p_out <= empty_fu_94;

    p_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln249_reg_504_pp0_iter12_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (icmp_ln249_reg_504_pp0_iter12_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out_ap_vld <= ap_const_logic_1;
        else 
            p_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln249_fu_247_p3 <= 
        add_ln249_fu_227_p2 when (icmp_ln250_fu_233_p2(0) = '1') else 
        ap_sig_allocacmp_row_pos_load;
    select_ln251_fu_439_p3 <= 
        div6_reg_569 when (and_ln251_1_fu_433_p2(0) = '1') else 
        p_load10_reg_576;
    select_ln52_fu_239_p3 <= 
        ap_const_lv7_0 when (icmp_ln250_fu_233_p2(0) = '1') else 
        ap_sig_allocacmp_col_pos_1_load;
        sext_ln253_fu_339_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_reg_558),64));

    tmp_10_fu_360_p4 <= bitcast_ln251_fu_357_p1(30 downto 23);
    tmp_24_fu_377_p4 <= bitcast_ln251_1_fu_374_p1(30 downto 23);
    tmp_fu_319_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_fu_319_p8 <= grp_fu_279_p2(2 - 1 downto 0);
    trunc_ln251_1_fu_387_p1 <= bitcast_ln251_1_fu_374_p1(23 - 1 downto 0);
    trunc_ln251_fu_370_p1 <= bitcast_ln251_fu_357_p1(23 - 1 downto 0);
    water_level_1_address0 <= zext_ln251_2_fu_309_p1(11 - 1 downto 0);
    water_level_1_ce0 <= water_level_1_ce0_local;

    water_level_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            water_level_1_ce0_local <= ap_const_logic_1;
        else 
            water_level_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    water_level_2_address0 <= zext_ln251_2_fu_309_p1(11 - 1 downto 0);
    water_level_2_ce0 <= water_level_2_ce0_local;

    water_level_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            water_level_2_ce0_local <= ap_const_logic_1;
        else 
            water_level_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    water_level_address0 <= zext_ln251_2_fu_309_p1(11 - 1 downto 0);
    water_level_ce0 <= water_level_ce0_local;

    water_level_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            water_level_ce0_local <= ap_const_logic_1;
        else 
            water_level_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln251_2_fu_309_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_458_p3),64));
end behav;
